# Generated by Django 4.1.6 on 2023-02-05 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(error_messages={'required': 'Le prénom est requis'}, max_length=30)),
                ('last_name', models.CharField(error_messages={'required': 'Le nom est requis'}, max_length=150)),
                ('email', models.EmailField(error_messages={'required': "L'email est requis", 'unique': "L'email est déjà utilisé"}, max_length=255, unique=True)),
                ('mobile_phone', models.CharField(error_messages={'required': 'Le numéro de téléphone mobile est requis'}, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', "Le numéro de téléphone mobile n'est pas valide")])),
                ('home_phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', "Le numéro de téléphone fixe n'est pas valide")])),
                ('adress', models.CharField(error_messages={'required': "L'adresse est requise"}, max_length=255)),
                ('zip_code', models.CharField(error_messages={'required': 'Le code postal est requis'}, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{5,10}$', "Le code postal n'est pas valide")])),
                ('city', models.CharField(error_messages={'required': 'La ville est requise'}, max_length=100)),
                ('country', models.CharField(choices=[('France', 'France'), ('Etats-Unis', 'Etats-Unis'), ('Angleterre', 'Angleterre'), ('Canada', 'Canada')], error_messages={'required': 'Le pays est requis'}, max_length=50)),
                ('kbis', models.CharField(error_messages={'required': 'Le numéro de KBIS est requis'}, max_length=100, validators=[django.core.validators.RegexValidator('^[0-9]{14}$', "Le numéro de KBIS n'est pas valide")])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
